apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-gateway" (tpl .Values.global.zeebe .) | quote }}
  labels:
    app.kubernetes.io/name: {{ include "zeebe-cluster.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ printf "%s-gateway" (tpl .Values.global.zeebe .) | quote }}
  annotations:
      {{- range $key, $value := .Values.annotations }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}   
spec:
  replicas: {{ .Values.gateway.replicas  }}
  selector:
    matchLabels:
      app: {{ printf "%s-gateway" (tpl .Values.global.zeebe .) | quote }}
  template:
    metadata:  
      labels:
        app.kubernetes.io/name: {{ include "zeebe-cluster.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ printf "%s-gateway" (tpl .Values.global.zeebe .) | quote }}
      annotations:
        {{- range $key, $value := .Values.gateway.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{  .Values.serviceHttpPort }}
              name: {{  default "http" .Values.serviceHttpName }}
            - containerPort: {{  .Values.serviceGatewayPort }}
              name: {{ default "gateway" .Values.serviceGatewayName  }}
            - containerPort: {{  .Values.serviceInternalPort }}
              name: {{ default "internal" .Values.serviceInternalName  }}
          env:
            - name: ZEEBE_STANDALONE_GATEWAY
              value: "true"
            - name: ZEEBE_GATEWAY_CLUSTER_CLUSTERNAME
              value: {{ tpl .Values.global.zeebe . }}  
            - name: ZEEBE_GATEWAY_CLUSTER_MEMBERID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ZEEBE_LOG_LEVEL
              value: {{ .Values.gateway.logLevel | quote }}
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.JavaOpts | quote }}
            - name: ZEEBE_GATEWAY_CLUSTER_CONTACTPOINT
              value: {{ tpl .Values.global.zeebe . }}:{{ .Values.serviceInternalPort }}
            - name: ZEEBE_GATEWAY_NETWORK_HOST
              value: 0.0.0.0
            - name: ZEEBE_GATEWAY_NETWORK_PORT
              value: {{  .Values.serviceGatewayPort | quote }}
            - name: ZEEBE_GATEWAY_CLUSTER_HOST
              value: 0.0.0.0
            - name: ZEEBE_GATEWAY_CLUSTER_PORT
              value: {{  .Values.serviceInternalPort | quote }}
            - name: ZEEBE_GATEWAY_MONITORING_HOST
              value: 0.0.0.0   
            - name: ZEEBE_GATEWAY_MONITORING_PORT
              value: {{  .Values.serviceHttpPort | quote }}
            {{- if .Values.gateway.env }}
            {{ toYaml .Values.gateway.env | indent 12 | trim }}
            {{- end }}
          securityContext:
            {{ toYaml .Values.podSecurityContext | indent 12 | trim }}
          readinessProbe:
            tcpSocket:
              port: {{ default "gateway" .Values.serviceGatewayName  }}
            initialDelaySeconds: 20
            periodSeconds: 5
